### ISSUE TITLE
Server crash on startup - ver 1.2.16 and 1.2.19

### ISSUE THREAD

**Issue by LesJ16** [ldtteam/Piston-Unlimited#27] opened 2022-12-02 18:44 UTC
Server suddenly started crashing on startup, I'm running Forge 43.1.65 and had Multi Piston ver 1.2.16 ALPHA installed.
Updating to 1.2.19 did not solve the issue.

Updated Minecolonies and Structurize to the most recent versions (Minecolonies 1.0.1127 BETA and Structurize 1.0.462 ALPHA) 

Only deleting Multi Pistons solved the crashes, but Minecolonies needs this mod

Log: https://paste.shockbyte.com/gadivememovipiguniyu

**Comment by MotionlessTrain** [comment] 2022-12-02 18:49
Duplicate of #25. It may help to downgrade forge

**Comment by Raycoms** [comment] 2022-12-03 10:11
fixed

**Closed by Raycoms** 2022-12-03 10:11 UTC
